# Evaluate E-Commerce Sales Data

## Objective

The objective of this analysis is to discover the best-selling products based on the sales data.

## Introduction

The dataset records all transactions of an online retail company from December 1, 2010 to December 9, 2011, covering the company's business data in different countries and regions around the world. The company primarily sells gifts for various occasions, including birthday gifts, wedding favors, Christmas gifts, etc. Its customer base mainly consists of wholesalers and individual consumers, with wholesalers making up a significant proportion.

Definition of each column as below,

InvoiceNo: Invoice number, 6 digits. It is the transactions unique identifier. If this number started with "c", it means the transaction was cancelled.  
StockCode: Product code. 5 digits, it is the products unique identifier.  
Description: Description of product.  
Quantity: Quantity of product in the transaction.  
InvoiceDate: Date & time of invoice.  
UnitPrice: Unit price in Pound (£).  
CustomerID: Customer ID. 5 digits. Customers unique identifier.  
Country: Country.

## Read The Data

In [1]:
import numpy as np
import pandas as pd

In [2]:
original_data = pd.read_csv("e_commerce.csv")
original_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

## Evaluate & Clean The Data

In [3]:
cleaned_data = original_data.copy()
cleaned_data.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

### Tidiness Of The Data

In [4]:
cleaned_data.sample(10)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
210055,555276,22583,PACK OF 6 HANDBAG GIFT BOXES,1,6/1/2011 17:28,4.96,NaN,United Kingdom
466170,576321,21822,GLITTER CHRISTMAS TREE WITH BELLS,1,11/14/2011 14:59,0.79,14953.0,United Kingdom
48415,540468,22173,METAL 4 HOOK HANGER FRENCH CHATEAU,1,1/7/2011 13:55,5.91,NaN,United Kingdom
287533,562106,23165,LARGE CERAMIC TOP STORAGE JAR,2,8/2/2011 15:19,1.65,14076.0,United Kingdom
237612,557877,47590B,PINK HAPPY BIRTHDAY BUNTING,3,6/23/2011 13:13,5.45,15379.0,United Kingdom
35240,539436,20975,12 PENCILS SMALL TUBE RED RETROSPOT,1,12/17/2010 14:49,1.28,NaN,United Kingdom
48681,540472,84970S,HANGING HEART ZINC T-LIGHT HOLDER,12,1/7/2011 14:22,0.85,18179.0,United Kingdom
100482,544817,22215,CAKE STAND WHITE TWO TIER LACE,4,2/23/2011 16:44,8.50,12437.0,France
521361,580361,35001G,HAND OPEN SHAPE GOLD,12,12/2/2011 16:25,1.25,14865.0,United Kingdom
244512,558534,20996,JAZZ HEARTS ADDRESS BOOK,24,6/30/2011 11:54,0.19,13988.0,United Kingdom

As seen from above, each variable as a column, each observation as a row, each cell contains a value, hence no issue.

### Cleanliness Of The Data

In [5]:
cleaned_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  object
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 33.1+ MB

Missing value exists in: Description & CustomerID

Dtype change to date: InvoiceDate  

Dtype change to str: CustomerID

#### Missing Value

In [6]:
# Missing value in Description

In [7]:
cleaned_data.query("Description.isna()")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
622,536414,22139,NaN,56,12/1/2010 11:52,0.0,NaN,United Kingdom
1970,536545,21134,NaN,1,12/1/2010 14:32,0.0,NaN,United Kingdom
1971,536546,22145,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1972,536547,37509,NaN,1,12/1/2010 14:33,0.0,NaN,United Kingdom
1987,536549,85226A,NaN,1,12/1/2010 14:34,0.0,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
535322,581199,84581,NaN,-2,12/7/2011 18:26,0.0,NaN,United Kingdom
535326,581203,23406,NaN,15,12/7/2011 18:31,0.0,NaN,United Kingdom
535332,581209,21620,NaN,6,12/7/2011 18:35,0.0,NaN,United Kingdom
536981,581234,72817,NaN,27,12/8/2011 10:33,0.0,NaN,United Kingdom
538554,581408,85175,NaN,20,12/8/2011 14:06,0.0,NaN,United Kingdom

There are 1454 rows of data with missing value in Description.  
From the output, all rows with missing value in Description have UnitPrice as 0.  
Hence, will further check if there is any rows with missing value in Description but not 0 in UnitPrice.

In [8]:
cleaned_data.query("(Description.isna()) & (UnitPrice != 0)")

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

Both Description & UniPrice are critical variables for the analysis. The data without these 2 information will not be effective, hence should remove those obervations with missing value in Description.

In [9]:
cleaned_data = cleaned_data.dropna(subset=['Description'])
cleaned_data['Description'].isna().sum()

np.int64(0)

In [10]:
# Missing value in CustomerID

In [11]:
cleaned_data.query("CustomerID.isna()")

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
1443,536544,21773,DECORATIVE ROSE BATHROOM BOTTLE,1,12/1/2010 14:32,2.51,NaN,United Kingdom
1444,536544,21774,DECORATIVE CATS BATHROOM BOTTLE,2,12/1/2010 14:32,2.51,NaN,United Kingdom
1445,536544,21786,POLKADOT RAIN HAT,4,12/1/2010 14:32,0.85,NaN,United Kingdom
1446,536544,21787,RAIN PONCHO RETROSPOT,2,12/1/2010 14:32,1.66,NaN,United Kingdom
1447,536544,21790,VINTAGE SNAP CARDS,9,12/1/2010 14:32,1.66,NaN,United Kingdom
...,...,...,...,...,...,...,...,...
541536,581498,85099B,JUMBO BAG RED RETROSPOT,5,12/9/2011 10:26,4.13,NaN,United Kingdom
541537,581498,85099C,JUMBO BAG BAROQUE BLACK WHITE,4,12/9/2011 10:26,4.13,NaN,United Kingdom
541538,581498,85150,LADIES & GENTLEMEN METAL SIGN,1,12/9/2011 10:26,4.96,NaN,United Kingdom
541539,581498,85174,S/4 CACTI CANDLES,1,12/9/2011 10:26,10.79,NaN,United Kingdom
541540,581498,DOT,DOTCOM POSTAGE,1,12/9/2011 10:26,1714.17,NaN,United Kingdom

CustomerID is not an essential variable to analyze best-selling product. When the value in CustomerID is missing, the analysis won't be affected. Hence should keep the rows with missing values in CustomerID.

#### Data Type

In [12]:
cleaned_data['InvoiceDate'] = pd.to_datetime(cleaned_data['InvoiceDate'])
cleaned_data['InvoiceDate']

0        2010-12-01 08:26:00
1        2010-12-01 08:26:00
2        2010-12-01 08:26:00
3        2010-12-01 08:26:00
4        2010-12-01 08:26:00
                 ...
541904   2011-12-09 12:50:00
541905   2011-12-09 12:50:00
541906   2011-12-09 12:50:00
541907   2011-12-09 12:50:00
541908   2011-12-09 12:50:00
Name: InvoiceDate, Length: 540455, dtype: datetime64[ns]

In [13]:
cleaned_data['CustomerID'] = cleaned_data['CustomerID'].astype(str)
cleaned_data['CustomerID']

0         17850.0
1         17850.0
2         17850.0
3         17850.0
4         17850.0
           ...
541904    12680.0
541905    12680.0
541906    12680.0
541907    12680.0
541908    12680.0
Name: CustomerID, Length: 540455, dtype: object

In [14]:
cleaned_data['CustomerID'] = cleaned_data['CustomerID'].str.slice(0,-2)
cleaned_data['CustomerID']

0         17850
1         17850
2         17850
3         17850
4         17850
          ...
541904    12680
541905    12680
541906    12680
541907    12680
541908    12680
Name: CustomerID, Length: 540455, dtype: object

#### Duplicated Value

InvoiceNo, StockCode & CustomerID are unique identifier. However, one single transaction may include several products, same product may exist in different transaction & same customer may have different transaction. Hence, duplicated values are expected in InvoiceNo, StockCode & CustomerID.

#### Non-standardize Value

Check if non-standardize values exist in Country.

In [15]:
cleaned_data['Country'].value_counts()

Country
United Kingdom          493812
Germany                   9495
France                    8557
EIRE                      8196
Spain                     2533
Netherlands               2371
Belgium                   2069
Switzerland               2002
Portugal                  1519
Australia                 1259
Norway                    1086
Italy                      803
Channel Islands            758
Finland                    695
Cyprus                     622
Sweden                     462
Unspecified                446
Austria                    401
Denmark                    389
Japan                      358
Poland                     341
Israel                     297
China                      288
Singapore                  229
USA                        218
UK                         211
Iceland                    182
Canada                     151
Greece                     146
Malta                      127
United States               73
United Arab Emirates        68
European Community          61
RSA                         58
Lebanon                     45
Lithuania                   35
Brazil                      32
Czech Republic              30
Bahrain                     19
Saudi Arabia                10
U.K.                         1
Name: count, dtype: int64

From above, United Kingdom, UK & U.K. refer to the same country. USA & United States refer to the same country.  
Hence, will replace UK & U.K. with United Kingdom, & replace USA with United States.

In [16]:
cleaned_data['Country'] = cleaned_data['Country'].replace(['UK', 'U.K.'], 'United Kingdom')

In [17]:
print(len(cleaned_data[cleaned_data['Country'] == 'UK']))
print(len(cleaned_data[cleaned_data['Country'] == 'U.K.']))

0
0

In [18]:
cleaned_data['Country'] = cleaned_data['Country'].replace('USA', 'United States')

In [19]:
print(len(cleaned_data[cleaned_data['Country'] == 'USA']))

0

#### Incorrect/Invalid Value

In [20]:
cleaned_data.describe()

            Quantity                    InvoiceDate      UnitPrice
count  540455.000000                         540455  540455.000000
mean        9.603129  2011-07-04 16:20:42.947035392       4.623519
min    -80995.000000            2010-12-01 08:26:00  -11062.060000
25%         1.000000            2011-03-28 11:49:00       1.250000
50%         3.000000            2011-07-20 11:38:00       2.080000
75%        10.000000            2011-10-19 11:49:00       4.130000
max     80995.000000            2011-12-09 12:50:00   38970.000000
std       218.007598                            NaN      96.889628

-ve value exists in Quantity & UnitPrice, this may affect subsequent analysis.

In [21]:
# -ve value in Quantity

In [22]:
cleaned_data.query('Quantity < 0')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
141,C536379,D,Discount,-1,2010-12-01 09:41:00,27.50,14527,United Kingdom
154,C536383,35004C,SET OF 3 COLOURED FLYING DUCKS,-1,2010-12-01 09:49:00,4.65,15311,United Kingdom
235,C536391,22556,PLASTERS IN TIN CIRCUS PARADE,-12,2010-12-01 10:24:00,1.65,17548,United Kingdom
236,C536391,21984,PACK OF 12 PINK PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
237,C536391,21983,PACK OF 12 BLUE PAISLEY TISSUES,-24,2010-12-01 10:24:00,0.29,17548,United Kingdom
...,...,...,...,...,...,...,...,...
540449,C581490,23144,ZINC T-LIGHT HOLDER STARS SMALL,-11,2011-12-09 09:57:00,0.83,14397,United Kingdom
541541,C581499,M,Manual,-1,2011-12-09 10:28:00,224.69,15498,United Kingdom
541715,C581568,21258,VICTORIAN SEWING BOX LARGE,-5,2011-12-09 11:57:00,10.95,15311,United Kingdom
541716,C581569,84978,HANGING HEART JAR T-LIGHT HOLDER,-1,2011-12-09 11:58:00,1.25,17315,United Kingdom
541717,C581569,20979,36 PENCILS TUBE RED RETROSPOT,-5,2011-12-09 11:58:00,1.25,17315,United Kingdom

From above, all observations with -ve value in Quantity have InvoiceNo start with C, meaning the transaction was cancelled.  
To further confirm, will check if there is any observation with -ve value in Quantiy but not InvoiceNo start with C.

In [23]:
cleaned_data.query('(Quantity < 0) & (InvoiceNo.str[0] != "C")')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
7313,537032,21275,?,-30,2010-12-03 16:50:00,0.0,n,United Kingdom
13217,537425,84968F,check,-20,2010-12-06 15:35:00,0.0,n,United Kingdom
13218,537426,84968E,check,-35,2010-12-06 15:36:00,0.0,n,United Kingdom
13264,537432,35833G,damages,-43,2010-12-06 16:10:00,0.0,n,United Kingdom
21338,538072,22423,faulty,-13,2010-12-09 14:10:00,0.0,n,United Kingdom
...,...,...,...,...,...,...,...,...
535333,581210,23395,check,-26,2011-12-07 18:36:00,0.0,n,United Kingdom
535335,581212,22578,lost,-1050,2011-12-07 18:38:00,0.0,n,United Kingdom
535336,581213,22576,check,-30,2011-12-07 18:38:00,0.0,n,United Kingdom
536908,581226,23090,missing,-338,2011-12-08 09:56:00,0.0,n,United Kingdom
538919,581422,23169,smashed,-235,2011-12-08 15:24:00,0.0,n,United Kingdom

From above, there are observations with -ve value in Quantity but InvoiceNo not start with C.  
However, extracted observations all show UnitPrice as 0.  
Hence, will add in the criteria of UnitPrice to check.

In [24]:
cleaned_data.query('(Quantity < 0) & (InvoiceNo.str[0] != "C") & (UnitPrice != 0)')

Empty DataFrame
Columns: [InvoiceNo, StockCode, Description, Quantity, InvoiceDate, UnitPrice, CustomerID, Country]
Index: []

From above, when Quanity is -ve value, one of the below criterias is met,  
- InvoiceNo starts with C, meaning the transaction was cancelled
- UnitPrice as 0

This means these observations are invalid transaction & should be removed.

In [25]:
cleaned_data = cleaned_data[cleaned_data['Quantity'] >= 0]
len(cleaned_data[cleaned_data['Quantity'] < 0])

0

In [26]:
# -ve value in UnitPrice

In [27]:
cleaned_data.query('UnitPrice < 0')

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
299983,A563186,B,Adjust bad debt,1,2011-08-12 14:51:00,-11062.06,n,United Kingdom
299984,A563187,B,Adjust bad debt,1,2011-08-12 14:52:00,-11062.06,n,United Kingdom

From the output, observations with -ve value in UnitPrice are for adjust bad debt, not valid transaction.  
Hence, should remove these observations.

In [28]:
cleaned_data = cleaned_data[cleaned_data['UnitPrice'] >= 0]
len(cleaned_data.query('UnitPrice < 0'))

0

In [29]:
# Save The File

In [30]:
cleaned_data.to_csv('e_commerce_cleaned.csv', index=False)

### Sort The Data

In [31]:
cleaned_data

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom
...,...,...,...,...,...,...,...,...
541904,581587,22613,PACK OF 20 SPACEBOY NAPKINS,12,2011-12-09 12:50:00,0.85,12680,France
541905,581587,22899,CHILDREN'S APRON DOLLY GIRL,6,2011-12-09 12:50:00,2.10,12680,France
541906,581587,23254,CHILDRENS CUTLERY DOLLY GIRL,4,2011-12-09 12:50:00,4.15,12680,France
541907,581587,23255,CHILDRENS CUTLERY CIRCUS PARADE,4,2011-12-09 12:50:00,4.15,12680,France
541908,581587,22138,BAKING SET 9 PIECE RETROSPOT,3,2011-12-09 12:50:00,4.95,12680,France

Sort out the total quantity of each product sold in each country.

In [32]:
product_quantity_groupby_country_and_stockcode = cleaned_data.groupby(['Country', 'StockCode'])['Quantity'].sum()
product_quantity_groupby_country_and_stockcode

Country      StockCode
Australia    15036        600
             15056BL        3
             16161P       400
             16169E        25
             20665          6
                         ...
Unspecified  85180A         2
             85180B         1
             85212         12
             85213         12
             85227         10
Name: Quantity, Length: 19664, dtype: int64

In [33]:
product_quantity_groupby_country_and_stockcode_df = product_quantity_groupby_country_and_stockcode.reset_index()
product_quantity_groupby_country_and_stockcode_df

           Country StockCode  Quantity
0        Australia     15036       600
1        Australia   15056BL         3
2        Australia    16161P       400
3        Australia    16169E        25
4        Australia     20665         6
...            ...       ...       ...
19659  Unspecified    85180A         2
19660  Unspecified    85180B         1
19661  Unspecified     85212        12
19662  Unspecified     85213        12
19663  Unspecified     85227        10

[19664 rows x 3 columns]

Sort out the best-selling product in each country.

In [34]:
country_best_selling_product = product_quantity_groupby_country_and_stockcode_df.groupby('Country')['Quantity'].max()
country_best_selling_product

Country
Australia                2952
Austria                   288
Bahrain                    96
Belgium                   480
Brazil                     24
Canada                    504
Channel Islands           407
China                     150
Cyprus                    384
Czech Republic             72
Denmark                   288
EIRE                     1852
European Community         24
Finland                   552
France                   4024
Germany                  1233
Greece                     48
Iceland                   240
Israel                    130
Italy                     240
Japan                    3408
Lebanon                    24
Lithuania                  48
Malta                      81
Netherlands              4801
Norway                    576
Poland                    168
Portugal                  240
RSA                        12
Saudi Arabia               12
Singapore                 384
Spain                    1089
Sweden                   2916
Switzerland               639
United Arab Emirates       72
United Kingdom          80995
United States              88
Unspecified                96
Name: Quantity, dtype: int64

Sort out the best-selling product in each country with stockcode.

In [35]:
country_best_selling_product_with_stockcode = pd.merge(product_quantity_groupby_country_and_stockcode_df, country_best_selling_product, on=['Country', 'Quantity'])
country_best_selling_product_with_stockcode

                 Country StockCode  Quantity
0              Australia     22492      2952
1                Austria     21918       288
2                Bahrain     23076        96
3                Belgium     21212       480
4                 Brazil     21430        24
..                   ...       ...       ...
57  United Arab Emirates     21700        72
58  United Arab Emirates     85215        72
59        United Kingdom     23843     80995
60         United States     23366        88
61           Unspecified     84077        96

[62 rows x 3 columns]

List out all available products.

In [36]:
stockcode_with_description = cleaned_data[['StockCode', 'Description']].drop_duplicates()
stockcode_with_description

       StockCode                          Description
0         85123A   WHITE HANGING HEART T-LIGHT HOLDER
1          71053                  WHITE METAL LANTERN
2         84406B       CREAM CUPID HEARTS COAT HANGER
3         84029G  KNITTED UNION FLAG HOT WATER BOTTLE
4         84029E       RED WOOLLY HOTTIE WHITE HEART.
...          ...                                  ...
535325     23404                                check
535334     22142                                check
537224    47591b             SCOTTIES CHILDRENS APRON
537621    85123A   CREAM HANGING HEART T-LIGHT HOLDER
540421     23843          PAPER CRAFT , LITTLE BIRDIE

[4319 rows x 2 columns]

Sort out the best-selling product in each country with product description.

In [37]:
country_best_selling_product_with_description = pd.merge(country_best_selling_product_with_stockcode, stockcode_with_description, on='StockCode')
country_best_selling_product_with_description

           Country StockCode  Quantity                         Description
0        Australia     22492      2952             MINI PAINT SET VINTAGE
1          Austria     21918       288    SET 12 KIDS COLOUR  CHALK STICKS
2          Bahrain     23076        96          ICE CREAM SUNDAE LIP GLOSS
3          Belgium     21212       480     PACK OF 72 RETROSPOT CAKE CASES
4           Brazil     21430        24  SET/3 RED GINGHAM ROSE STORAGE BOX
..             ...       ...       ...                                 ...
83  United Kingdom     23843     80995         PAPER CRAFT , LITTLE BIRDIE
84   United States     23366        88      SET 12 COLOURING PENCILS DOILY
85   United States     23366        88        SET 12 COLOUR PENCILS DOILEY
86   United States     23366        88     SET 12 COLOURING PENCILS DOILEY
87     Unspecified     84077        96   WORLD WAR 2 GLIDERS ASSTD DESIGNS

[88 rows x 4 columns]

There are duplicated values in Description, hence will remove duplicates according to the unique identifier StockCode.

In [38]:
country_best_selling_product_with_description = country_best_selling_product_with_description.drop_duplicates(subset=['Country', 'StockCode'])
country_best_selling_product_with_description

,Country,StockCode,Quantity,Description
0,Australia,22492,2952,MINI PAINT SET VINTAGE
1,Austria,21918,288,SET 12 KIDS COLOUR CHALK STICKS
2,Bahrain,23076,96,ICE CREAM SUNDAE LIP GLOSS
3,Belgium,21212,480,PACK OF 72 RETROSPOT CAKE CASES
4,Brazil,21430,24,SET/3 RED GINGHAM ROSE STORAGE BOX
...,...,...,...,...
80,United Arab Emirates,21700,72,BIG DOUGHNUT FRIDGE MAGNETS
82,United Arab Emirates,85215,72,ASSORTED CHEESE FRIDGE MAGNETS
83,United Kingdom,23843,80995,"PAPER CRAFT , LITTLE BIRDIE"
84,United States,23366,88,SET 12 COLOURING PENCILS DOILY
87,Unspecified,84077,96,WORLD WAR 2 GLIDERS ASSTD DESIGNS

The best-selling product in each country are shown in above dataframe.